// AUTOGENERATED - DO NOT EDIT

package client

import (
	"encoding/json"

	"github.com/Arman92/go-tdlib/v2/tdlib"
)

// GetChatListsToAddChat Returns chat lists to which the chat can be added. This is an offline request
// @param chatID Chat identifier
func (client *Client) GetChatListsToAddChat(chatID int64) (*tdlib.ChatLists, error) {
	result, err := client.SendAndCatch(tdlib.UpdateData{
		"@type":   "getChatListsToAddChat",
		"chat_id": chatID,
	})

	if err != nil {
		return nil, err
	}

	if result.Data["@type"].(string) == "error" {
		return nil, tdlib.RequestError{Code: int(result.Data["code"].(float64)), Message: result.Data["message"].(string)}
	}

	var chatLists tdlib.ChatLists
	err = json.Unmarshal(result.Raw, &chatLists)
	return &chatLists, err

}
