// AUTOGENERATED - DO NOT EDIT

package client

import (
	"encoding/json"
	"fmt"

	"github.com/Arman92/go-tdlib/tdlib"
)

// GetChatFilter Returns information about a chat filter by its identifier
// @param chatFilterID Chat filter identifier
func (client *Client) GetChatFilter(chatFilterID int32) (*tdlib.ChatFilter, error) {
	result, err := client.SendAndCatch(tdlib.UpdateData{
		"@type":          "getChatFilter",
		"chat_filter_id": chatFilterID,
	})

	if err != nil {
		return nil, err
	}

	if result.Data["@type"].(string) == "error" {
		return nil, fmt.Errorf("error! code: %d msg: %s", result.Data["code"], result.Data["message"])
	}

	var chatFilterDummy tdlib.ChatFilter
	err = json.Unmarshal(result.Raw, &chatFilterDummy)
	return &chatFilterDummy, err

}
