// AUTOGENERATED - DO NOT EDIT

package tdlib

// ChatInviteLinkMember Describes a chat member joined a chat by an invite link
type ChatInviteLinkMember struct {
	tdCommon
	UserID         int64 `json:"user_id"`          // User identifier
	JoinedChatDate int32 `json:"joined_chat_date"` // Point in time (Unix timestamp) when the user joined the chat
}

// MessageType return the string telegram-type of ChatInviteLinkMember
func (chatInviteLinkMember *ChatInviteLinkMember) MessageType() string {
	return "chatInviteLinkMember"
}

// NewChatInviteLinkMember creates a new ChatInviteLinkMember
//
// @param userID User identifier
// @param joinedChatDate Point in time (Unix timestamp) when the user joined the chat
func NewChatInviteLinkMember(userID int64, joinedChatDate int32) *ChatInviteLinkMember {
	chatInviteLinkMemberTemp := ChatInviteLinkMember{
		tdCommon:       tdCommon{Type: "chatInviteLinkMember"},
		UserID:         userID,
		JoinedChatDate: joinedChatDate,
	}

	return &chatInviteLinkMemberTemp
}
