// AUTOGENERATED - DO NOT EDIT

package tdlib

// ChatInviteLink Contains a chat invite link
type ChatInviteLink struct {
	tdCommon
	InviteLink string `json:"invite_link"` // Chat invite link
}

// MessageType return the string telegram-type of ChatInviteLink
func (chatInviteLink *ChatInviteLink) MessageType() string {
	return "chatInviteLink"
}

// NewChatInviteLink creates a new ChatInviteLink
//
// @param inviteLink Chat invite link
func NewChatInviteLink(inviteLink string) *ChatInviteLink {
	chatInviteLinkTemp := ChatInviteLink{
		tdCommon:   tdCommon{Type: "chatInviteLink"},
		InviteLink: inviteLink,
	}

	return &chatInviteLinkTemp
}
