// AUTOGENERATED - DO NOT EDIT

package tdlib

// ChatInviteLinkCounts Contains a list of chat invite link counts
type ChatInviteLinkCounts struct {
	tdCommon
	InviteLinkCounts []ChatInviteLinkCount `json:"invite_link_counts"` // List of invite linkcounts
}

// MessageType return the string telegram-type of ChatInviteLinkCounts
func (chatInviteLinkCounts *ChatInviteLinkCounts) MessageType() string {
	return "chatInviteLinkCounts"
}

// NewChatInviteLinkCounts creates a new ChatInviteLinkCounts
//
// @param inviteLinkCounts List of invite linkcounts
func NewChatInviteLinkCounts(inviteLinkCounts []ChatInviteLinkCount) *ChatInviteLinkCounts {
	chatInviteLinkCountsTemp := ChatInviteLinkCounts{
		tdCommon:         tdCommon{Type: "chatInviteLinkCounts"},
		InviteLinkCounts: inviteLinkCounts,
	}

	return &chatInviteLinkCountsTemp
}
